// import 'normalize-scss'
import '../style/index.scss'
import "../img/favicon.png"
import "../img/logo.png"
import "../img/facebook.svg"
import "../img/instagram.svg"
import "../img/google-maps.svg"
import "../img/telephone.svg"
import "../img/open-menu-1.svg"
import "../img/open-menu-1.png"
import "../img/address.svg"
import "../img/productivity.svg"
import "../img/mail.svg"
import "../img/phone.svg"
import "../img/time-and-date.svg"
import "../img/1.jpg"
import "../img/2.jpg"
import "../img/3.jpg"
import "../img/arrow.svg"

import "../img/satara_logo.png"
import "../img/laRossa_logo.png"
import "../img/pannochka_logo.png"
import "../img/nanoestetic_logo.png"
import "../img/misfill_logo.png"